# Example Secrets to create manually
# 
# IMPORTANT: This file contains example values and should NOT be applied directly.
# Use the create-secrets.sh script or create the Secrets manually with your real values.
#
# To create the Secrets manually:
#
# 1. Main Secret (BETTER_AUTH_SECRET and DATABASE_URL):
#    kubectl create secret generic deco-mcp-mesh-secrets \
#      --from-literal=BETTER_AUTH_SECRET='your-secret-here' \
#      --from-literal=DATABASE_URL='postgresql://user:pass@host:5432/db' \
#      -n deco-mcp-mesh
#
# 2. Secret for sensitive authConfig values:
#    kubectl create secret generic deco-mcp-mesh-auth-secrets \
#      --from-literal=googleClientId='your-google-client-id' \
#      --from-literal=googleClientSecret='your-google-client-secret' \
#      --from-literal=githubClientId='your-github-client-id' \
#      --from-literal=githubClientSecret='your-github-client-secret' \
#      --from-literal=resendApiKey='your-resend-api-key' \
#      -n deco-mcp-mesh

---
# Main Secret - BETTER_AUTH_SECRET and DATABASE_URL
apiVersion: v1
kind: Secret
metadata:
  name: deco-mcp-mesh-secrets
  namespace: deco-mcp-mesh
type: Opaque
stringData:
  BETTER_AUTH_SECRET: "SUBSTITUA_PELO_SEU_SECRET_AQUI"
  DATABASE_URL: "postgresql://usuario:senha@host:5432/database"

---
# Secret for sensitive authConfig values
# Contains clientId and clientSecret to keep everything in one place
apiVersion: v1
kind: Secret
metadata:
  name: deco-mcp-mesh-auth-secrets
  namespace: deco-mcp-mesh
type: Opaque
stringData:
  googleClientId: "SUBSTITUA_PELO_CLIENT_ID_DO_GOOGLE"
  googleClientSecret: "SUBSTITUA_PELO_CLIENT_SECRET_DO_GOOGLE"
  githubClientId: "SUBSTITUA_PELO_CLIENT_ID_DO_GITHUB"
  githubClientSecret: "SUBSTITUA_PELO_CLIENT_SECRET_DO_GITHUB"
  resendApiKey: "SUBSTITUA_PELA_API_KEY_DO_RESEND"

