{{- if not .Values.secret.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-deco-mcp-mesh.fullname" . }}-secrets
  labels:
    {{- include "chart-deco-mcp-mesh.labels" . | nindent 4 }}
type: Opaque
stringData:
  BETTER_AUTH_SECRET: {{ .Values.secret.BETTER_AUTH_SECRET | quote }}
  {{- if eq (lower (default "sqlite" .Values.database.engine)) "postgresql" }}
  # DATABASE_URL goes in Secret when PostgreSQL (contains sensitive credentials)
  DATABASE_URL: {{ include "chart-deco-mcp-mesh.databaseUrl" . | trim | quote }}
  {{- end }}
{{- end }}
